environment:
  PYPI_USER: "andrewzwicky"
  PYPI_PW:
    secure: "UYwQCnByKXfEv0Z72TOSKw=="
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python37-x64\\Scripts\\pip"

skip_commits:
  files:
    - 'docs/*'
    - 'replay_pickles/*'
    - 'examples/*'
    - 'README.md'
    - 'README.rst'
    - 'LICENSE'

platform:
  - x64

install:
  - "%PYTHON%\\python --version"
  - "%PIP% --version"
  - "%PIP% install --disable-pip-version-check --user --upgrade pip"
  - "git clone -q --depth=1 --branch=master https://github.com/LtHummus/SpyPartyParse.git C:\projects\spypartyparse"
  - "appveyor DownloadFile https://digi.bib.uni-mannheim.de/tesseract/tesseract-ocr-w64-setup-v4.1.0.20190314.exe"
  - ps: ".\\tesseract-ocr-w64-setup-v4.1.0.20190314.exe /S /v /qn"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;C:\\Program Files\\Tesseract-OCR;C:\\projects\\spypartyparse;%PATH%"
  - "%PIP% install -e .[plot,retrieve,parse,test]"

build: false

test_script:
  - "pytest triple_agent --cov=triple_agent"
  - "pylint triple_agent"
  - "black triple_agent --check"
