environment:
  PYPI_USER: "andrewzwicky"
  PYPI_PW:
    secure: "UYwQCnByKXfEv0Z72TOSKw=="
  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python37-x64\\Scripts\\pip"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python38-x64\\Scripts\\pip"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
      PIP: "C:\\Python39-x64\\Scripts\\pip"


skip_commits:
  files:
    - 'docs/**'
    - 'replay_pickles/**'
    - '**/*.ipynb'
    - 'examples/**'
    - 'README.md'
    - 'README.rst'
    - 'LICENSE'

platform:
  - x64

install:
  - "%PYTHON%\\python --version"
  - "%PIP% --version"
  - "git clone -q --depth=1 --branch=master https://github.com/andrewzwicky/SpyPartyParse.git C:\\projects\\spypartyparse"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PYTHONPATH=%PYTHONPATH%;C:\\projects\\spypartyparse"
  - "%PIP% install -e .[plot,retrieve,parse,test] --quiet"
  - "%PIP% list installed"

build: false

test_script:
  - "black triple_agent --check"
  - "pylint triple_agent"
  - "vulture triple_agent vulture_whitelist.py"
  # confirm no import errors in vulture_whitelist
  - "%PYTHON%\\python vulture_whitelist.py"
  - "pytest triple_agent --cov=triple_agent --cov-report term-missing:skip-covered"
