import pytest

from triple_agent.classes.characters import Characters
from triple_agent.classes.roles import Roles
from triple_agent.classes.timeline import TimelineEvent, Timeline
from triple_agent.classes.books import Books

@pytest.mark.parsing
@pytest.mark.quick
def test_reclassify_suspected_double_agents():
    input_events = [
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:30.0",
            event="marked less suspicious.",
            cast_name=(Characters.Teal,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="spy cast.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="ambassador cast.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="double agent cast.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="suspected double agent cast.",
            cast_name=(Characters.Teal,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="suspected double agent cast.",
            cast_name=(Characters.Oprah,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduction target cast.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.General,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Alice,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Irish,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Bling,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Morgan,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Helen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="bug ambassador selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="contact double agent selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="transfer microfilm selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="swap statue selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="inspect 3 statues selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduce target selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="purloin guest list selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="fingerprint ambassador selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="bug ambassador enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="contact double agent enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="transfer microfilm enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="swap statue enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="inspect 3 statues enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduce target enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="purloin guest list enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="fingerprint ambassador enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="04:30.0",
            event="game started.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:28.4",
            event="spy player takes control from ai.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:27.3",
            event="marked suspicious.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:24.1",
            event="get book from bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:23.3",
            event="marked less suspicious.",
            cast_name=(Characters.Oprah,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:22.5",
            event="marked less suspicious.",
            cast_name=(Characters.Teal,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:20.1",
            event="marked less suspicious.",
            cast_name=(Characters.Damon,),
            role=(Roles.Staff,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:16.5",
            event="marked book.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:16.3",
            event="marked book.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:15.9",
            event="marked book.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:15.7",
            event="marked book.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:13.6",
            event="marked book.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:13.2",
            event="marked book.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:12.7",
            event="marked suspicious.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:09.0",
            event="marked suspicious.",
            cast_name=(Characters.Toby,),
            role=(Roles.Staff,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:06.1",
            event="marked suspicious.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:02.9",
            event="marked less suspicious.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:01.0",
            event="put book in bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green, Books.Yellow),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:01.0",
            event="transferred microfilm.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green, Books.Yellow),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:49.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:37.4",
            event="marked book.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:37.3",
            event="marked book.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:33.1",
            event="marked book.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:25.8",
            event="interrupted speaker.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:23.7",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:19.2",
            event="marked book.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:19.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:19.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:17.7",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:16.8",
            event="marked suspicious.",
            cast_name=(Characters.Bling,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:11.8",
            event="picked up statue.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:10.2",
            event="marked book.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:08.6",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:07.8",
            event="action test white: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:07.8",
            event="marked spy suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:03.6",
            event="held statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:03.1",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:02.3",
            event="action test green: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:00.7",
            event="right statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:00.4",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:59.6",
            event="action test white: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:57.4",
            event="left statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:57.4",
            event="all statues inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:56.3",
            event="put back statue.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:43.0",
            event="marked neutral suspicion.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:42.8",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:42.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:41.3",
            event="marked suspicious.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:39.7",
            event="marked book.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:36.1",
            event="marked suspicious.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:31.9",
            event="marked neutral suspicion.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:28.2",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:25.7",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:25.7",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:11.7",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:09.8",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:09.8",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.7",
            event="action test white: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.7",
            event="flirt with seduction target: 34%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.1",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:06.3",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:57.1",
            event="flirtation cooldown expired.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:50.9",
            event="marked book.",
            cast_name=(Characters.General,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:48.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:47.1",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:47.1",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:46.0",
            event="action test green: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:46.0",
            event="flirt with seduction target: 85%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:45.4",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.2",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.2",
            event="spy joined conversation with double agent.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.1",
            event="flirtation cooldown expired.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:32.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:28.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:28.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:26.8",
            event="marked suspicious.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:22.4",
            event="marked book.",
            cast_name=(Characters.Helen,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:20.9",
            event="marked suspicious.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:20.3",
            event="marked suspicious.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:11.1",
            event="action triggered: contact double agent",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:11.1",
            event="real banana bread started.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:09.8",
            event="action test ignored: contact double agent",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:03.1",
            event="banana bread uttered.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:02.6",
            event="double agent contacted.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.9",
            event="marked less suspicious.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.8",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.6",
            event="marked less suspicious.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.3",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.3",
            event="spy left conversation with double agent.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.1",
            event="marked less suspicious.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:00.0",
            event="marked spy less suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:59.2",
            event="marked less suspicious.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:58.6",
            event="marked spy suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:52.3",
            event="marked book.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:51.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:50.5",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:50.5",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="action test white: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="flirt with seduction target: 100%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="target seduced.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.0",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:47.8",
            event="marked less suspicious.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:46.0",
            event="marked less suspicious.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:41.1",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:29.0",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:26.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:20.2",
            event="got drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:20.2",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:15.1",
            event="gulped drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:12.6",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:07.3",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:07.3",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:06.0",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:02.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:01.3",
            event="action triggered: purloin guest list",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.1",
            event="action test green: purloin guest list",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.1",
            event="guest list purloin pending.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="00:00.1",
            event="missions completed. countdown pending.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:04.3",
            event="marked less suspicious.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:04.5",
            event="marked less suspicious.",
            cast_name=(Characters.Irish,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:11.0",
            event="overtime!",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="-00:12.2",
            event="guest list purloined.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:12.2",
            event="missions completed. 10 second countdown.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:14.1",
            event="took shot.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="-00:15.1",
            event="get book from bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:18.3",
            event="sniper shot spy.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
    ]

    expected_events = [
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:30.0",
            event="marked less suspicious.",
            cast_name=(Characters.Teal,),
            role=(Roles.SuspectedDoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="spy cast.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="ambassador cast.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="double agent cast.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="suspected double agent cast.",
            cast_name=(Characters.Teal,),
            role=(Roles.SuspectedDoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="suspected double agent cast.",
            cast_name=(Characters.Oprah,),
            role=(Roles.SuspectedDoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduction target cast.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.General,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Alice,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Irish,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Bling,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Morgan,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="civilian cast.",
            cast_name=(Characters.Helen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="bug ambassador selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="contact double agent selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="transfer microfilm selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="swap statue selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="inspect 3 statues selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduce target selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="purloin guest list selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="fingerprint ambassador selected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="bug ambassador enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="contact double agent enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="transfer microfilm enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="swap statue enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="inspect 3 statues enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="seduce target enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="purloin guest list enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:30.0",
            event="fingerprint ambassador enabled.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="04:30.0",
            event="game started.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:28.4",
            event="spy player takes control from ai.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:27.3",
            event="marked suspicious.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:24.1",
            event="get book from bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:23.3",
            event="marked less suspicious.",
            cast_name=(Characters.Oprah,),
            role=(Roles.SuspectedDoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:22.5",
            event="marked less suspicious.",
            cast_name=(Characters.Teal,),
            role=(Roles.SuspectedDoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:20.1",
            event="marked less suspicious.",
            cast_name=(Characters.Damon,),
            role=(Roles.Staff,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:16.5",
            event="marked book.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:16.3",
            event="marked book.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:15.9",
            event="marked book.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:15.7",
            event="marked book.",
            cast_name=(Characters.Smallman,),
            role=(Roles.Civilian,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:13.6",
            event="marked book.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:13.2",
            event="marked book.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:12.7",
            event="marked suspicious.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:09.0",
            event="marked suspicious.",
            cast_name=(Characters.Toby,),
            role=(Roles.Staff,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:06.1",
            event="marked suspicious.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="04:02.9",
            event="marked less suspicious.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:01.0",
            event="put book in bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green, Books.Yellow),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="04:01.0",
            event="transferred microfilm.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Green, Books.Yellow),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:49.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:37.4",
            event="marked book.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:37.3",
            event="marked book.",
            cast_name=(Characters.Plain,),
            role=(Roles.Ambassador,),
            books=(Books.Green,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:33.1",
            event="marked book.",
            cast_name=(Characters.Taft,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:25.8",
            event="interrupted speaker.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:23.7",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:19.2",
            event="marked book.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:19.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:19.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:17.7",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:16.8",
            event="marked suspicious.",
            cast_name=(Characters.Bling,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:11.8",
            event="picked up statue.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:10.2",
            event="marked book.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:08.6",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:07.8",
            event="action test white: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="03:07.8",
            event="marked spy suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:03.6",
            event="held statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:03.1",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:02.3",
            event="action test green: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:00.7",
            event="right statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="03:00.4",
            event="action triggered: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:59.6",
            event="action test white: inspect statues",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:57.4",
            event="left statue inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:57.4",
            event="all statues inspected.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:56.3",
            event="put back statue.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:43.0",
            event="marked neutral suspicion.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:42.8",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:42.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:41.3",
            event="marked suspicious.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:39.7",
            event="marked book.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:36.1",
            event="marked suspicious.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="02:31.9",
            event="marked neutral suspicion.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:29.8",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:28.2",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:25.7",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:25.7",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:11.7",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:09.8",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:09.8",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.7",
            event="action test white: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.7",
            event="flirt with seduction target: 34%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:08.1",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="02:06.3",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:57.1",
            event="flirtation cooldown expired.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:50.9",
            event="marked book.",
            cast_name=(Characters.General,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:48.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:47.1",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:47.1",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:46.0",
            event="action test green: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:46.0",
            event="flirt with seduction target: 85%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:45.4",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.2",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.2",
            event="spy joined conversation with double agent.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:36.1",
            event="flirtation cooldown expired.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:32.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:28.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:28.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:26.8",
            event="marked suspicious.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:22.4",
            event="marked book.",
            cast_name=(Characters.Helen,),
            role=(Roles.Civilian,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:20.9",
            event="marked suspicious.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:20.3",
            event="marked suspicious.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:11.1",
            event="action triggered: contact double agent",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:11.1",
            event="real banana bread started.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:09.8",
            event="action test ignored: contact double agent",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:03.1",
            event="banana bread uttered.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:02.6",
            event="double agent contacted.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.9",
            event="marked less suspicious.",
            cast_name=(Characters.Rocker,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.8",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.6",
            event="marked less suspicious.",
            cast_name=(Characters.Queen,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.3",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="01:01.3",
            event="spy left conversation with double agent.",
            cast_name=(Characters.Sikh,),
            role=(Roles.DoubleAgent,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:01.1",
            event="marked less suspicious.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="01:00.0",
            event="marked spy less suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:59.2",
            event="marked less suspicious.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:58.6",
            event="marked spy suspicious.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:52.3",
            event="marked book.",
            cast_name=(Characters.Wheels,),
            role=(Roles.Civilian,),
            books=(Books.Blue,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:51.3",
            event="spy enters conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:50.5",
            event="action triggered: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:50.5",
            event="begin flirtation with seduction target.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="action test white: seduce target",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="flirt with seduction target: 100%",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.6",
            event="target seduced.",
            cast_name=(Characters.Carlos,),
            role=(Roles.SeductionTarget,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:49.0",
            event="stopped talking.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:47.8",
            event="marked less suspicious.",
            cast_name=(Characters.Salmon,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="00:46.0",
            event="marked less suspicious.",
            cast_name=(Characters.Boots,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:41.1",
            event="spy leaves conversation.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:29.0",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:26.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:20.2",
            event="got drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:20.2",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:15.1",
            event="gulped drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:12.6",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:07.3",
            event="action triggered: check watch",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:07.3",
            event="watch checked.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:06.0",
            event="request drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:02.1",
            event="waiter offered drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:01.3",
            event="action triggered: purloin guest list",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.1",
            event="action test green: purloin guest list",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.1",
            event="guest list purloin pending.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="00:00.1",
            event="missions completed. countdown pending.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.0",
            event="rejected drink from waiter.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="00:00.0",
            event="waiter stopped offering drink.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:04.3",
            event="marked less suspicious.",
            cast_name=(Characters.Sari,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:04.5",
            event="marked less suspicious.",
            cast_name=(Characters.Irish,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:11.0",
            event="overtime!",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="-00:12.2",
            event="guest list purloined.",
            cast_name=(Characters.Disney,),
            role=(Roles.Civilian,),
            books=(None,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:12.2",
            event="missions completed. 10 second countdown.",
            cast_name=(None,),
            role=(None,),
            books=(None,),
        ),
        TimelineEvent(
            actor="sniper",
            _raw_time_str="-00:14.1",
            event="took shot.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
        TimelineEvent(
            actor="spy",
            _raw_time_str="-00:15.1",
            event="get book from bookcase.",
            cast_name=(None,),
            role=(None,),
            books=(Books.Yellow,),
        ),
        TimelineEvent(
            actor="game",
            _raw_time_str="-00:18.3",
            event="sniper shot spy.",
            cast_name=(Characters.Duke,),
            role=(Roles.Spy,),
            books=(None,),
        ),
    ]

    timeline = Timeline(input_events)

    for in_event, exp_event in zip(timeline, expected_events):
        assert in_event == exp_event




